// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen1

type Photo struct {
	ID       string `json:"id"`
	User     *User  `json:"user"`
	URL      string `json:"url"`
	Comment  string `json:"comment"`
	Rating   int    `json:"rating"`
	Liked    bool   `json:"liked"`
	Followed bool   `json:"followed"`
}

type User struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}
