// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen3

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Avatar   string `json:"avatar"`
	Followed bool   `json:"followed"`
}
